### ISSUE TITLE
Microsoft Graph missing in config > Prototypes

### ISSUE THREAD

**Issue by obsjmartin** [PaloAltoNetworks/minemeld-msgraph-secapi#6]
## Describe the bug

MineMeld Nodes for Microsoft Graph Security API not showing under prototypes

## Expected behavior
After installing and activating the MineMeld Nodes for Microsoft Graph Security API via github and activating the plugin, Microsoft Graph SECAPI output should be listed under config > prototypes. 

The Microsoft Graph SECAPI output should be listed under config > prototypes
## Current behavior
Microsoft Graph SECAPI output should be listed under config > prototypes is missing.

After activating the plugin and navigating to Config > prototypes, the Microsoft Graph SECAPI output is missing in the list. Searching for Microsoft yields no results, and scrubbing through the available list, it is missing.
## Steps to reproduce
https://live.paloaltonetworks.com/t5/minemeld-articles/send-iocs-to-microsoft-graph-api-with-minemeld/ta-p/258540

1.
2.
3.
4.

## Your Environment
Ubuntu 16.04 server

- Version used: v0.3
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by fvigo** [comment]
Hi @obsjmartin , please try the following:
- Make sure the extension is activat
- Restart the Minemeld engine
- Restart the Minemeld webui
- Completely refresh the browser page (i.e. close the tab and open a new one, or do ctrl-F5)

Please update if that works.

Thanks

**Comment by obsjmartin** [comment]
I was able to resolve it. Turns out ADAL had to be installed. So after installing pip and ADAL the plug-in was loaded and worked.

Thanks so much for your response.

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by fvigo** [comment]
Great to hear, thanks for letting us know!

Closing this issue.
